# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3cf010ff21a674ab5088440666ef64a88d796b3454877a54a33a083647339b6bf5f6ceefbe6052ed9db80ab1cb65018d237eab9625263a206b87f136f5aca05

test:
  secret_key_base: e6fb333be6c461f6160ba69e1c04fa9439115a6e891e9bfee115704ff84c8ec7b1aa14cd0364dc9613d9064b6c2b5ace7109f3abb21a67fa1b6c0b15f249c98a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
